"""ændre tilmelder_id

Revision ID: 622340b61444
Revises: ad4cc2f6b6b3
Create Date: 2022-06-09 09:16:26.378804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '622340b61444'
down_revision = 'ad4cc2f6b6b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tilmeldte_ibfk_4', 'tilmeldte', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('tilmeldte_ibfk_4', 'tilmeldte', 'profile', ['tilmelder_id'], ['id'])
    # ### end Alembic commands ###
