"""Administrator

Revision ID: 904ad08900a1
Revises: bb779e520d1b
Create Date: 2022-06-07 13:08:34.784227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '904ad08900a1'
down_revision = 'bb779e520d1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('administrator', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile', 'administrator')
    # ### end Alembic commands ###
