"""tilmelder_id

Revision ID: ad4cc2f6b6b3
Revises: 8c30292b1f95
Create Date: 2022-06-09 09:09:15.583379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad4cc2f6b6b3'
down_revision = '8c30292b1f95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tilmeldte', sa.Column('tilmelder_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tilmeldte', 'profile', ['tilmelder_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tilmeldte', type_='foreignkey')
    op.drop_column('tilmeldte', 'tilmelder_id')
    # ### end Alembic commands ###
