"""Banedata

Revision ID: bb779e520d1b
Revises: e45cb2266648
Create Date: 2022-06-04 11:08:52.665951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb779e520d1b'
down_revision = 'e45cb2266648'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('baner', sa.Column('kort_navn_pdf', sa.String(length=150), nullable=True))
    op.add_column('baner', sa.Column('kort_navn_png', sa.String(length=150), nullable=True))
    op.add_column('baner', sa.Column('bane_beskrivelse', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('baner', 'bane_beskrivelse')
    op.drop_column('baner', 'kort_navn_png')
    op.drop_column('baner', 'kort_navn_pdf')
    # ### end Alembic commands ###
