"""Klarmeldt

Revision ID: e45cb2266648
Revises: 90bf25e44123
Create Date: 2022-06-02 15:49:58.794068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e45cb2266648'
down_revision = '90bf25e44123'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('konkurrence_data', sa.Column('klarmeldt', sa.Boolean(), nullable=True))
    op.add_column('konkurrence_data', sa.Column('resultatKlarmeldt', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('konkurrence_data', 'resultatKlarmeldt')
    op.drop_column('konkurrence_data', 'klarmeldt')
    # ### end Alembic commands ###
