"""empty message

Revision ID: 5d6624a1b165
Revises: 1648ea506684
Create Date: 2022-06-01 13:08:15.801500

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5d6624a1b165'
down_revision = '1648ea506684'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('klubber',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('Klubnavn', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('loeb',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('skov', sa.String(length=150), nullable=True),
    sa.Column('dato', sa.Date(), nullable=True),
    sa.Column('klub', sa.String(length=100), nullable=True),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('andet', sa.String(length=250), nullable=True),
    sa.Column('emitenheder', sa.String(length=4), nullable=True),
    sa.Column('kort', sa.Boolean(), nullable=True),
    sa.Column('klarmeldt', sa.Boolean(), nullable=True),
    sa.Column('baner', sa.String(length=200), nullable=True),
    sa.Column('kortURL', sa.String(length=100), nullable=True),
    sa.Column('klub_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['klub_id'], ['klubber.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('navn', sa.String(length=150), nullable=True),
    sa.Column('adresse', sa.String(length=150), nullable=True),
    sa.Column('klub', sa.String(length=100), nullable=True),
    sa.Column('brik', sa.String(length=6), nullable=True),
    sa.Column('telefonnummer', sa.String(length=12), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('kunNavn', sa.Boolean(), nullable=True),
    sa.Column('mails', sa.Boolean(), nullable=True),
    sa.Column('mails_res', sa.Boolean(), nullable=True),
    sa.Column('date_created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('klub_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['klub_id'], ['klubber.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('filer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fil', sa.LargeBinary(), nullable=True),
    sa.Column('filnavn', sa.String(length=250), nullable=True),
    sa.Column('banenavn', sa.String(length=50), nullable=True),
    sa.Column('url', sa.String(length=528), nullable=True),
    sa.Column('filbeskrivelse', sa.String(length=150), nullable=True),
    sa.Column('download', sa.Integer(), nullable=True),
    sa.Column('loeb_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['loeb_id'], ['loeb.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tilmeldte',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('navn', sa.String(length=150), nullable=True),
    sa.Column('tilmelder', sa.Boolean(), nullable=True),
    sa.Column('bane', sa.String(length=100), nullable=True),
    sa.Column('brik', sa.String(length=6), nullable=True),
    sa.Column('telefonnummer', sa.String(length=12), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('klub_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['klub_id'], ['klubber.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('runners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bane', sa.String(length=10), nullable=True),
    sa.Column('tilmeldte_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('loeb_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['loeb_id'], ['loeb.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.ForeignKeyConstraint(['tilmeldte_id'], ['tilmeldte.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('klub')
    op.add_column('medlemmer', sa.Column('klubber_id', sa.Integer(), nullable=True))
    op.drop_constraint('medlemmer_ibfk_1', 'medlemmer', type_='foreignkey')
    op.create_foreign_key(None, 'medlemmer', 'klubber', ['klubber_id'], ['id'])
    op.drop_column('medlemmer', 'klub_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medlemmer', sa.Column('klub_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'medlemmer', type_='foreignkey')
    op.create_foreign_key('medlemmer_ibfk_1', 'medlemmer', 'klub', ['klub_id'], ['id'])
    op.drop_column('medlemmer', 'klubber_id')
    op.create_table('klub',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('langtnavn', mysql.VARCHAR(length=80), nullable=True),
    sa.Column('kortnavn', mysql.VARCHAR(length=40), nullable=True),
    sa.Column('tom', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('kreds', mysql.VARCHAR(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('runners')
    op.drop_table('tilmeldte')
    op.drop_table('filer')
    op.drop_table('profile')
    op.drop_table('loeb')
    op.drop_table('klubber')
    # ### end Alembic commands ###
